name: sshu-dev-pipeline
run-name: ${{ github.actor }} triggered dev pipeline with ${{ github.event_name }} to main
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirement.txt
      - name: Install with poetry
        run: poetry install
      - name: Run Test
        run: PYTHONPATH=./src poetry run pytest -vv

  build_linux_glibc:
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build docker image to build binary
        run: docker build -t local/sshu-build:latest -f build/Dockerfile.linux_glibc .
      - name: Build binary
        run: docker run --rm -it -v ./bin:/dist local/sshu-build:latest
      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: sshu-linux-glibc
          path: bin/sshu

  build_linux_musl:
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build docker image to build binary
        run: docker build -t local/sshu-build:latest -f build/Dockerfile.linux_musl .
      - name: Build binary
        run: docker run --rm -it -v ./bin:/dist local/sshu-build:latest
      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: sshu-linux-musl
          path: bin/sshu

  build_windows:
    needs: test
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          py -m pip install --upgrade pip
          pip install -r requirement.txt
      - name: Install with poetry
        run: poetry install
      - name: Build binary
        run: PYTHONPATH=./src poetry run pyinstaller --name sshu --distpath ./bin -p ./src/sshu --onefile ./src/sshu/cli.py

  build_macos:
    needs: test
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
      - name: Install with poetry
        run: poetry install
      - name: Build binary
        run: PYTHONPATH=./src poetry run pyinstaller --name sshu --distpath ./bin -p ./src/sshu --onefile ./src/sshu/cli.py
